PyMySQL is an interface for connecting to a MySQL database server from Python. It implements the Python Database API v2. 0 and contains a pure-Python MySQL client library. The goal of PyMySQL is to be a drop-in replacement for MySQLdb.

In [2]:
!pip install pymysql

Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Datamites\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Datamites\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Datamites\anaconda3\Lib\site-packages)

In [3]:
import pymysql
import pandas as pd

In [4]:
## making connections to database server
connection=pymysql.connect(host = 'localhost',user='root',password='abc123')

In [5]:
# Create a cursor object to execute SQL queries
cursor = connection.cursor()

## Create Database

In [6]:
##Creating Database
cursor.execute("CREATE DATABASE College6")

1

In [7]:
cursor.execute('show databases')
for i in cursor:
    print(i)

('college',)
('college1',)
('college2',)
('college3',)
('college4',)
('college5',)
('college6',)
('employee_details',)
('information_schema',)
('mysql',)
('performance_schema',)
('school',)
('sys',)
('university',)

In [8]:
## making connections to database server
connection=pymysql.connect(host = 'localhost',user='root',password='abc123', database='college6' )

In [9]:
# Create a cursor object to execute SQL queries
cursor = connection.cursor()

## Create Table

In [10]:
create_table_query = """
CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50),
    age INT,
    city VARCHAR(50)
)
"""
cursor.execute(create_table_query)

# SQL Query to insert a record
insert_query = "INSERT INTO users (name, age, city) VALUES (%s, %s, %s)"
values = ('Alice', 30, 'New York')

# Execute the query
cursor.execute(insert_query, values)

# Commit the transaction to save changes to the database
connection.commit()

print("Record inserted successfully")

Record inserted successfully

In [11]:
db_tables=pd.read_sql_query('show tables',connection)
print(db_tables)

  Tables_in_college6
0              users

C:\Users\Datamites\AppData\Local\Temp\ipykernel_4656\3349514694.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  db_tables=pd.read_sql_query('show tables',connection)

## Show Details from Table

In [13]:
query = "select * from users"
output = pd.read_sql(query,connection)
print(output.shape)
output

(1, 4)

C:\Users\Datamites\AppData\Local\Temp\ipykernel_4656\4207674100.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  output = pd.read_sql(query,connection)

   id   name  age      city
0   1  Alice   30  New York

## Inserting Multiple Values

In [14]:
# Insert multiple records
values = [
    ('Bob', 25, 'Los Angeles'),
    ('Charlie', 35, 'Chicago'),
    ('Diana', 28, 'San Francisco')
]
cursor.executemany(insert_query, values)
connection.commit()

In [16]:
# SQL Query to select all records
select_query = "SELECT * FROM users"

# Execute the query
cursor.execute(select_query)

# Fetch all the rows from the result
rows = cursor.fetchall()

# Print the results
for row in rows:
    print(row)

(1, 'Alice', 30, 'New York')
(2, 'Bob', 25, 'Los Angeles')
(3, 'Charlie', 35, 'Chicago')
(4, 'Diana', 28, 'San Francisco')

In [17]:
query = "select * from users"
output = pd.read_sql(query,connection)
print(output.shape)
output

(4, 4)

C:\Users\Datamites\AppData\Local\Temp\ipykernel_4656\4207674100.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  output = pd.read_sql(query,connection)

   id     name  age           city
0   1    Alice   30       New York
1   2      Bob   25    Los Angeles
2   3  Charlie   35        Chicago
3   4    Diana   28  San Francisco

## Using Where Clause

In [18]:
# SQL Query to select specific records (e.g., users older than 30)
select_query = "SELECT * FROM users Where AGE > %s"
cursor.execute(select_query, (30,))

# Fetch and print the filtered rows
rows = cursor.fetchall()
for row in rows:
    print(row)

(3, 'Charlie', 35, 'Chicago')

## Updating Records

In [19]:
# SQL Query to update a record
update_query = "UPDATE users SET city = %s WHERE name = %s"
values = ('Las Vegas', 'Bob')

# Execute the update query
cursor.execute(update_query, values)

# Commit the transaction
connection.commit()

print("Record updated successfully")

Record updated successfully

In [20]:
query = "select * from users"
output = pd.read_sql(query,connection)
print(output.shape)
output

(4, 4)

C:\Users\Datamites\AppData\Local\Temp\ipykernel_4656\4207674100.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  output = pd.read_sql(query,connection)

   id     name  age           city
0   1    Alice   30       New York
1   2      Bob   25      Las Vegas
2   3  Charlie   35        Chicago
3   4    Diana   28  San Francisco

## Deleting Record

In [21]:
# SQL Query to delete a record
delete_query = "DELETE FROM users WHERE name = %s"
value = ('Charlie',)

# Execute the delete query
cursor.execute(delete_query, value)

# Commit the transaction
connection.commit()

print("Record deleted successfully")

Record deleted successfully

In [22]:
query = "select * from users"
output = pd.read_sql(query,connection)
print(output.shape)
output

(3, 4)

C:\Users\Datamites\AppData\Local\Temp\ipykernel_4656\4207674100.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  output = pd.read_sql(query,connection)

   id   name  age           city
0   1  Alice   30       New York
1   2    Bob   25      Las Vegas
2   4  Diana   28  San Francisco

# Some other Queries

In [23]:
query = "select * from users where age<30 and name='Bob'"
output = pd.read_sql(query,connection)
print(output.shape)
output

(1, 4)

C:\Users\Datamites\AppData\Local\Temp\ipykernel_4656\3449080189.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  output = pd.read_sql(query,connection)

   id name  age       city
0   2  Bob   25  Las Vegas

In [36]:
query = "select DISTINCT city from users"
output = pd.read_sql(query,connection)
print(output.shape)
output

(3, 1)

C:\Users\Datamites\AppData\Local\Temp\ipykernel_10352\2256329539.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  output = pd.read_sql(query,connection)

            city
0       New York
1      Las Vegas
2  San Francisco

In [24]:
query = "select count(*) from users where city='New York'"
output = pd.read_sql(query,connection)
print(output.shape)
output

(1, 1)

C:\Users\Datamites\AppData\Local\Temp\ipykernel_4656\1484527538.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  output = pd.read_sql(query,connection)

   count(*)
0         1

In [26]:
query = "select * from users order by city desc"
output = pd.read_sql(query,connection)
print(output.shape)
output

(3, 4)

C:\Users\Datamites\AppData\Local\Temp\ipykernel_4656\88184897.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  output = pd.read_sql(query,connection)

   id   name  age           city
0   4  Diana   28  San Francisco
1   1  Alice   30       New York
2   2    Bob   25      Las Vegas

## Closing Connection

In [27]:
# Close the cursor and connection
cursor.close()
connection.close()